# Generated by Django 3.0.5 on 2020-04-21 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField(default=0.0)),
                ('productWeight', models.FloatField(null=True)),
                ('productImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
