# Generated by Django 3.0.5 on 2020-04-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200423_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='productWeight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
