# Generated by Django 3.0.5 on 2020-04-24 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200423_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productCartDesc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productShortDesc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productUpdateDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
