# Generated by Django 3.0.5 on 2020-04-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200424_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productUpdateDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
