# Generated by Django 3.0.5 on 2020-04-24 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200424_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productUpdateDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
