# Generated by Django 3.0.5 on 2020-04-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200424_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productLiveStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='productLocation',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productStock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
