# Generated by Django 3.0.5 on 2020-04-27 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20200424_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productUpdateDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderAmount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('orderShipName', models.CharField(max_length=100)),
                ('orderShipAddress1', models.CharField(max_length=100)),
                ('orderShipAddress2', models.CharField(blank=True, max_length=100, null=True)),
                ('orderCity', models.CharField(blank=True, max_length=100, null=True)),
                ('orderState', models.CharField(blank=True, max_length=100, null=True)),
                ('orderZip', models.CharField(blank=True, max_length=100, null=True)),
                ('orderCountry', models.CharField(max_length=100)),
                ('orderPhone', models.CharField(max_length=100)),
                ('orderShippingAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('orderTax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('orderEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('orderDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('orderShipped', models.BooleanField(default=False)),
                ('orderTrackingNumber', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('detailId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detailName', models.CharField(max_length=250)),
                ('detailPrice', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('detailQuantity', models.IntegerField(default=0)),
                ('detailOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
            ],
        ),
    ]
