# Generated by Django 3.0.5 on 2020-04-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200427_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productStock',
            field=models.IntegerField(default=0),
        ),
    ]
