# Generated by Django 3.0.5 on 2020-04-29 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200429_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTrackingNumber',
            field=models.UUIDField(default=uuid.UUID('eb8b580c-df13-4699-b26a-c233f7d5044c')),
        ),
    ]
