# Generated by Django 3.0.5 on 2020-04-29 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200429_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTrackingNumber',
            field=models.UUIDField(default=uuid.UUID('964fdccf-cb90-479a-a004-592d0722523a'), unique=True),
        ),
    ]
