# Generated by Django 3.0.5 on 2020-04-29 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200429_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTrackingNumber',
            field=models.UUIDField(default=uuid.UUID('ec41a370-ba98-4bbd-96e9-86d2b105fb9b'), unique=True),
        ),
    ]
