# Generated by Django 3.0.5 on 2020-04-30 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200429_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTrackingNumber',
            field=models.UUIDField(default=uuid.UUID('9fe1499a-78bb-4612-a63d-a2782b3e8236'), unique=True),
        ),
    ]
