# Generated by Django 3.0.5 on 2020-04-30 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200430_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTrackingNumber',
            field=models.UUIDField(default=uuid.UUID('e1182ca9-940d-4882-9c33-134e67f9a71f'), unique=True),
        ),
    ]
