# Generated by Django 3.0.5 on 2020-04-30 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200430_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderTrackingNumber',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
