# Generated by Django 3.0.5 on 2020-04-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200430_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
